services:
  - type: web
    name: savanesprl-api
    runtime: image
    repo: https://github.com/Mdav10/www-savanesprl
    plan: free
    dockerCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: DG_USERNAME
        value: OsiasHab
      - key: DG_PASSWORD
        value: 08800Osi
      - key: SECRET_KEY
        value: savanes_super_secret_key_2024_secure
      - key: DATABASE_URL
        value: postgresql://mlw_attack_user:ShJf3c9NA4Jf1ADITLYh3fIlHc7akHXC@dpg-d8063p9j2pic73f1mm40-a/mlw_attack
